// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg8kZVyiS_nrkckhyeCPsxzVZT-P7kUvQ',
    appId: '1:231813671344:web:1002172e673d8cbdf6ce75',
    messagingSenderId: '231813671344',
    projectId: 'chat-app-c05ed',
    authDomain: 'chat-app-c05ed.firebaseapp.com',
    storageBucket: 'chat-app-c05ed.appspot.com',
    measurementId: 'G-FW1W5Z9R8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChCUVScScXl-p6dIqbbOjP3d53n0v6g-Q',
    appId: '1:231813671344:android:44e807ad8c93dd9bf6ce75',
    messagingSenderId: '231813671344',
    projectId: 'chat-app-c05ed',
    storageBucket: 'chat-app-c05ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo4L8DJUNUU6luceOUu69bWQ-6f3fH_uA',
    appId: '1:231813671344:ios:b54ee1ec104dce99f6ce75',
    messagingSenderId: '231813671344',
    projectId: 'chat-app-c05ed',
    storageBucket: 'chat-app-c05ed.appspot.com',
    iosBundleId: 'com.example.schoolarChat',
  );
}
